// authCode.js

const uri = "https://stockgenius.ai/?s=ok&code=200&auth_code=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhcGkubG9naW4uZnllcnMuaW4iLCJpYXQiOjE3MTkzMTYzMzUsImV4cCI6MTcxOTM0NjMzNSwibmJmIjoxNzE5MzE1NzM1LCJhdWQiOiJbXCJ4OjBcIiwgXCJ4OjFcIiwgXCJ4OjJcIiwgXCJkOjFcIiwgXCJkOjJcIiwgXCJ4OjFcIiwgXCJ4OjBcIl0iLCJzdWIiOiJhdXRoX2NvZGUiLCJkaXNwbGF5X25hbWUiOiJZQTE0MjIxIiwib21zIjoiSzEiLCJoc21fa2V5IjoiZDk1ZDQxNmY0NzZmYWJmZTM3NWMwMWI5MDdlMjAyNzY5MTA1MmI3NmFmYjk5NDRmMjAyMDVmMmUiLCJub25jZSI6IiIsImFwcF9pZCI6IjcxMFJZQVVJNVoiLCJ1dWlkIjoiMzMyMjZhYmU0NzY0NGI1M2I4M2FiOTk3ZTA1NjFlZWEiLCJpcEFkZHIiOiIwLjAuMC4wIiwic2NvcGUiOiIifQ.NM_mn4dStekabJd-lTmDLcxe_caOHmq_zykQxTg_RC0&state=sample_state";

const urlParams = new URLSearchParams(uri);
const authCode = urlParams.get('auth_code');

module.exports = authCode;
